# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5c897bd0ccefc1c1064ff3fda831aa1b9309bf79d29962d22ce5245fdbc30aee6fceab0608ad978b4d6173f03b7ba87bf44c98d457e45d94570d5001b76fc3d

test:
  secret_key_base: cc10af0b73b719a3d41a898fd153d7eec4745b9091eef9d3475958f79151e38de3e032149e6878e5c30b8da455dedad371e11d6c2c9c00146f2e468752eb39bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
